### ISSUE TITLE
Uncaught SyntaxError: Unexpected token export error?

### ISSUE THREAD

**Issue by THREKASHRI** [arnthor3/react-liquidchart#2]
When i use this package i get the error Uncaught SyntaxError: Unexpected token export. i don't know what is the issue can u please tell it

**Comment by arnthor3** [comment]
Whats your setup? This sounds like your project is not set up to use es6, could that be the case?

**Comment by THREKASHRI** [comment]
My project setup is for es6. My webpack is for 1.4 version.

**Comment by arnthor3** [comment]
ok cool, could you put the project up on github so I can clone it and see whats up?

**Comment by THREKASHRI** [comment]
Ya .... I have pushed into the github. The repo is
https://github.com/THREKASHRI/liquidchart



Can u please check and tell the issues.

**Comment by arnthor3** [comment]
I will check this when I am off work. in about 5 hours or so. You can try if you are - if you are in a rush - to fork the library and install it locally and see if it works for you that way. Another option would be to use another library react-liquidgauge, you might have better luck there.

**Comment by THREKASHRI** [comment]
It's ok .. u please check and inform me. I get the same error in that
package too. So if your giving some solution it will be better for us.

**Comment by arnthor3** [comment]
I cloned the project and tried to get this working, but no success. Sorry, this is tied to your setup.

My advise would be to use create-react-app and swap to the other version, react-liquid-gauge. I will not be working on this anytime soon again I am afraid. 

I am closing this, good luck and I hope you get your project going.
